import { Deal, DealStatus, PayPlan } from '../types';
import { calculateDealCommission } from '../lib/commissionLogic';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * StripeItExportSystem
 * Handles the transformation of structured dealership data into portable formats.
 */

export const exportService = {
  /**
   * Generates a CSV string from an array of objects.
   */
  generateCSV(data: any[], headers: { key: string; label: string }[]): string {
    if (!data || data.length === 0) return '';

    const headerRow = headers.map(h => `"${h.label}"`).join(',');
    const rows = data.map(row => {
      return headers.map(h => {
        const value = h.key.split('.').reduce((obj, key) => obj?.[key], row);
        const formattedValue = value === null || value === undefined ? '' : value;
        // Escape quotes and wrap in quotes
        return `"${String(formattedValue).replace(/"/g, '""')}"`;
      }).join(',');
    });

    return [headerRow, ...rows].join('\n');
  },

  /**
   * Triggers a browser download of a CSV file.
   */
  downloadCSV(csvContent: string, fileName: string) {
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `${fileName}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  },

  generatePDF(
    data: any[],
    headers: { key: string; label: string }[],
    title: string,
    dateRange: string
  ): jsPDF {
    const doc = new jsPDF({ orientation: 'landscape' });
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header bar
    doc.setFillColor(0, 212, 255); // brand-primary cyan
    doc.rect(0, 0, pageWidth, 22, 'F');

    // Title
    doc.setTextColor(10, 15, 30);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('STRIPE IT', 14, 9);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(title.toUpperCase(), 14, 16);

    // Date range — right aligned
    doc.setFontSize(8);
    doc.text(dateRange, pageWidth - 14, 13, { align: 'right' });

    // Table
    const tableHeaders = headers.map(h => h.label);
    const tableRows = data.map(row =>
      headers.map(h => {
        const value = h.key.split('.').reduce(
          (obj: any, key: string) => obj?.[key], row
        );
        return value === null || value === undefined ? '' : String(value);
      })
    );

    autoTable(doc, {
      head: [tableHeaders],
      body: tableRows,
      startY: 28,
      theme: 'grid',
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [0, 212, 255],
        fontStyle: 'bold',
        fontSize: 7,
        cellPadding: 4
      },
      bodyStyles: {
        fillColor: [15, 23, 42],
        textColor: [200, 210, 230],
        fontSize: 7,
        cellPadding: 3
      },
      alternateRowStyles: {
        fillColor: [20, 30, 50]
      },
      styles: {
        lineColor: [30, 41, 59],
        lineWidth: 0.1
      },
      margin: { left: 14, right: 14 }
    });

    // Footer
    const pageCount = (doc.internal as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(100, 116, 139);
      doc.text(
        `Page ${i} of ${pageCount} — Generated by Stripe It`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: 'center' }
      );
    }

    return doc;
  },

  downloadPDF(
    data: any[],
    headers: { key: string; label: string }[],
    title: string,
    dateRange: string,
    fileName: string
  ): void {
    const doc = exportService.generatePDF(
      data, headers, title, dateRange
    );
    doc.save(`${fileName}.pdf`);
  },

  /**
   * Standardize deal data for export.
   */
  prepareDealExportData(deals: Deal[], payPlan?: PayPlan | null) {
    return deals.map(deal => {
      const commission = payPlan ? calculateDealCommission(deal, payPlan, deals) : null;
      const splitRatio = deal.isSplitDeal ? (deal.splitPercentage || 50) / 100 : 1;
      
      return {
        date: deal.date,
        customer: deal.customerName,
        vehicle: deal.purchasedVehicle,
        stock: deal.stockNumber || '',
        condition: deal.newOrUsed.toUpperCase(),
        status: deal.status,
        frontGross: deal.frontEndGross * splitRatio,
        backGross: deal.backEndGross * splitRatio,
        totalGross: (deal.frontEndGross + deal.backEndGross) * splitRatio,
        estCommission: commission ? commission.finalPayout : 0,
        isSplit: deal.isSplitDeal ? `YES (${deal.splitPercentage || 50}%)` : 'NO'
      };
    });
  }
};
